//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day6_Assignment_01_23_07_2018
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Info
    {
        public int Roll_No { get; set; }
        public string Name { get; set; }
        public System.DateTime Dob { get; set; }
        public string Gender { get; set; }
        public string Course { get; set; }
        public string Semester { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
    }
}
